config/routes.rb
Rails.application.routes.draw do
  get '/tasks/overdue', to: 'tasks#overdue'
  get '/tasks/completed', to: 'tasks#completed'
  get '/tasks/statistics', to: 'tasks#statistics'
  get '/tasks/priority', to:'tasks#priority'
  

  resources :tasks do
   

    resources :users
  end

  get "up" => "rails/health#show", as: :rails_health_check
 
  post '/users', to: 'users#create'
  post '/tasks/:id/assign', to: 'users#assign'
  get   '/users/:id/tasks', to: 'users#alltasks'
  put   '/tasks/:id/progress', to: 'tasks#progress'
  put '/tasks/:id/duedate', to: 'tasks#duedate'
  put '/tasks/:id/todaydate', to: 'tasks#todaydate'
  get '/tasks/status/:status', to: 'tasks#tasksofstatus'
  put '/tasks/:id', to: 'tasks#update'


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user
 
end

app/models/user.rb
class User < ApplicationRecord
    has_many :tasks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :null_session, if: -> { request.format.json? }
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: %i[ show edit update destroy ], except: %i[completed statistics priority ]

  def index
    @tasks = Task.all
    render json: { message: 'Successfull', task: @tasks }, status: :ok
  end


  def show
  end


  def new
    @task = Task.new
  end


  def edit
  end


  def create
    @task = Task.new(task_params)

   
      if @task.save
   
        render json: { message: "successfully", task: @task }, status: :ok
      else
        render json: @task.errors, status: :unprocessable_entity 
      end
    
  end


  def update
    
      if @task.update(task_params)
        if @task.saved_change_to_attribute?(:status) && @task.status == "completed"
          @task.completed_date = Date.today
          @task.save
        end
        render json: { message: "successfully", task: @task }, status: :ok
      else
        render json: @task.errors, status: :unprocessable_entity 
      end
    
  end

  def progress
    
    task = Task.find(params[:id])
    
    if task.present?
      task.update(progress: params[:progress])
      render json: { message: 'Successfull', task: task }, status: :ok
    else
      render json: { error: 'Failed to insert userid', errors: task.errors }, status: :unprocessable_entity
    end
  end

 

  def duedate
    task = Task.find_by(id: params[:id])
    
    if task.present?
      task.update(due_date: params[:due_date])
      render json: { message: 'Successfull', task: task }, status: :ok
    else
      render json: { error: 'Failed to insert duedate', errors: task.errors }, status: :unprocessable_entity
    end

  end
 

  def tasksofstatus
    status = params[:status]

    if status.present?
      tasks = Task.where(status: status) 
    else
      tasks = Task.all
    end

    render json: tasks
  end
  

  def overdue
 
     task = Task.where("due_date <?", current_date)

     render json: {task: task}
  end

  def completed
    #http://localhost:3000/tasks/completed?start_date=2024-03-10&end_date=2024-03-15
    start_date = params[:start_date]
    
    end_date = params[:end_date]

    if start_date.present? && end_date.present?
     
      completed_tasks = Task.where(status: "completed")
                            .where("completed_date >= ?", start_date)
                            .where("completed_date <= ?", end_date)
      
      render json: completed_tasks
    else
      render json: { error: "Both startDate and endDate parameters are required" }, status: :unprocessable_entity
    end
  end

  def statistics

    task =Task.all
    total_count = task.count
    completed_count = Task.where(status: "completed").count
    percentage = (completed_count.to_f/total_count.to_f) * 100
    render json: {total_count: total_count,completed_count: completed_count,percentage: percentage }
   

  end
  def priority
   
    medium = Task.where(priority: "medium").order(due_date: :asc)
    low = Task.where(priority: "low").order(due_date: :asc)
    high = Task.where(priority: "high").order(due_date: :asc)

    all_tasks = {
      medium_priority: medium,
      low_priority: low,
      high_priority: high
    }

    render json: all_tasks

  

  end

  def destroy
    @task.destroy
    render json: { message: 'Successfully deleted', task: @task }, status: :ok

  end

  private
   
    def set_task
      @task = Task.find(params[:id])
    end

    require 'date'
    def current_date
      Date.today
    end


    
    def task_params
      params.require(:task).permit(:title, :description, :due_date, :status, :progress, :priority, :due_date, :user_id,:completed_date)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]


  def index
    @users = User.all
  end

  def show
    
  end

  
  def new
    @user = User.new
  end

  
  def edit
  end

 
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
       
        format.json { render :show, status: :created, location: @user }
      else
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def assign

    user = User.find_by(id: params[:user_id])
    task = Task.find_by(id: params[:id])
    if user.present? && task.present?
      task.update(user_id: params[:user_id])
      render json: { message: 'Successfully', task: task }, status: :ok
    else
      render json: { error: 'Failed', errors: task.errors }, status: :unprocessable_entity
    end
  end

  def alltasks

    task = Task.where(user_id: params[:id])
    if task.present? 
      render json: { message: 'Found all tasks of user successfully', task: task }, status: :ok
    else
      render json: { error: 'Failed to find tasks', errors: task.errors }, status: :unprocessable_entity
    end

  end
  
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

 
  def destroy
    @user.destroy!

    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    
    def set_user
      @user = User.find(params[:id])
    end

    
    def user_params
      params.require(:user).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
# <!DOCTYPE html>
# <html>
#   <head>
#     <title>TaskManager</title>
#     <meta name="viewport" content="width=device-width,initial-scale=1">
#     <%= csrf_meta_tags %>
#     <%= csp_meta_tag %>

#     <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
#     <%= javascript_importmap_tags %>
#   </head>

#   <body>
#     <%= yield %>
#   </body>
# </html>

app/views/tasks/_form.html.erb
# <%= form_with(model: task) do |form| %>
#   <% if task.errors.any? %>
#     <div style="color: red">
#       <h2><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h2>

#       <ul>
#         <% task.errors.each do |error| %>
#           <li><%= error.full_message %></li>
#         <% end %>
#       </ul>
#     </div>
#   <% end %>

#   <div>
#     <%= form.label :title, style: "display: block" %>
#     <%= form.text_field :title %>
#   </div>

#   <div>
#     <%= form.label :description, style: "display: block" %>
#     <%= form.text_field :description %>
#   </div>

#   <div>
#     <%= form.label :dueDate, style: "display: block" %>
#     <%= form.date_field :dueDate %>
#   </div>

#   <div>
#     <%= form.label :status, style: "display: block" %>
#     <%= form.text_field :status %>
#   </div>

#   <div>
#     <%= form.label :progress, style: "display: block" %>
#     <%= form.text_field :progress %>
#   </div>

#   <div>
#     <%= form.label :priority, style: "display: block" %>
#     <%= form.text_field :priority %>
#   </div>

#   <div>
#     <%= form.label :created_date, style: "display: block" %>
#     <%= form.date_field :created_date %>
#   </div>

#   <div>
#     <%= form.label :user_id, style: "display: block" %>
#     <%= form.text_field :user_id %>
#   </div>

#   <div>
#     <%= form.submit %>
#   </div>
# <% end %>

app/views/tasks/_task.html.erb
# <div id="<%= dom_id task %>">
#   <p>
#     <strong>Title:</strong>
#     <%= task.title %>
#   </p>

#   <p>
#     <strong>Description:</strong>
#     <%= task.description %>
#   </p>

#   <p>
#     <strong>Duedate:</strong>
#     <%= task.dueDate %>
#   </p>

#   <p>
#     <strong>Status:</strong>
#     <%= task.status %>
#   </p>

#   <p>
#     <strong>Progress:</strong>
#     <%= task.progress %>
#   </p>

#   <p>
#     <strong>Priority:</strong>
#     <%= task.priority %>
#   </p>

#   <p>
#     <strong>Created date:</strong>
#     <%= task.created_date %>
#   </p>

#   <p>
#     <strong>User:</strong>
#     <%= task.user_id %>
#   </p>

# </div>

app/views/tasks/edit.html.erb
# <h1>Editing task</h1>

# <%= render "form", task: @task %>

# <br>

# <div>
#   <%= link_to "Show this task", @task %> |
#   <%= link_to "Back to tasks", tasks_path %>
# </div>

app/views/tasks/index.html.erb
# <p style="color: green"><%= notice %></p>

# <h1>Tasks</h1>

# <div id="tasks">
#   <% @tasks.each do |task| %>
#     <%= render task %>
#     <p>
#       <%= link_to "Show this task", task %>
#     </p>
#   <% end %>
# </div>

# <%= link_to "New task", new_task_path %>

app/views/tasks/new.html.erb
# <h1>New task</h1>

# <%= render "form", task: @task %>

# <br>

# <div>
#   <%= link_to "Back to tasks", tasks_path %>
# </div>

app/views/tasks/show.html.erb
# <p style="color: green"><%= notice %></p>

# <%= render @task %>

# <div>
#   <%= link_to "Edit this task", edit_task_path(@task) %> |
#   <%= link_to "Back to tasks", tasks_path %>

#   <%= button_to "Destroy this task", @task, method: :delete %>
# </div>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
  <p>
    <strong>Name:</strong>
    <%= user.name %>
  </p>

</div>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Show this user", @user %> |
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Users</h1>

<div id="users">
  <% @users.each do |user| %>
    <%= render user %>
    <p>
      <%= link_to "Show this user", user %>
    </p>
  <% end %>
</div>

<%= link_to "New user", new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @user %>

<div>
  <%= link_to "Edit this user", edit_user_path(@user) %> |
  <%= link_to "Back to users", users_path %>

  <%= button_to "Destroy this user", @user, method: :delete %>
</div>